// Code generated by protoc-gen-go. DO NOT EDIT.
// source: r5.proto

package r5

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreatePeerRequest struct {
	Audio                bool                         `protobuf:"varint,1,opt,name=audio,proto3" json:"audio,omitempty"`
	Video                bool                         `protobuf:"varint,2,opt,name=video,proto3" json:"video,omitempty"`
	AudioRtp             *CreatePeerRequest_RtpTarget `protobuf:"bytes,3,opt,name=audio_rtp,json=audioRtp,proto3" json:"audio_rtp,omitempty"`
	VideoRtp             *CreatePeerRequest_RtpTarget `protobuf:"bytes,4,opt,name=video_rtp,json=videoRtp,proto3" json:"video_rtp,omitempty"`
	IceServerUri         string                       `protobuf:"bytes,5,opt,name=ice_server_uri,json=iceServerUri,proto3" json:"ice_server_uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *CreatePeerRequest) Reset()         { *m = CreatePeerRequest{} }
func (m *CreatePeerRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePeerRequest) ProtoMessage()    {}
func (*CreatePeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_09bcb7a7db58f7d2, []int{0}
}

func (m *CreatePeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePeerRequest.Unmarshal(m, b)
}
func (m *CreatePeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePeerRequest.Marshal(b, m, deterministic)
}
func (m *CreatePeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePeerRequest.Merge(m, src)
}
func (m *CreatePeerRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePeerRequest.Size(m)
}
func (m *CreatePeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePeerRequest proto.InternalMessageInfo

func (m *CreatePeerRequest) GetAudio() bool {
	if m != nil {
		return m.Audio
	}
	return false
}

func (m *CreatePeerRequest) GetVideo() bool {
	if m != nil {
		return m.Video
	}
	return false
}

func (m *CreatePeerRequest) GetAudioRtp() *CreatePeerRequest_RtpTarget {
	if m != nil {
		return m.AudioRtp
	}
	return nil
}

func (m *CreatePeerRequest) GetVideoRtp() *CreatePeerRequest_RtpTarget {
	if m != nil {
		return m.VideoRtp
	}
	return nil
}

func (m *CreatePeerRequest) GetIceServerUri() string {
	if m != nil {
		return m.IceServerUri
	}
	return ""
}

type CreatePeerRequest_RtpTarget struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePeerRequest_RtpTarget) Reset()         { *m = CreatePeerRequest_RtpTarget{} }
func (m *CreatePeerRequest_RtpTarget) String() string { return proto.CompactTextString(m) }
func (*CreatePeerRequest_RtpTarget) ProtoMessage()    {}
func (*CreatePeerRequest_RtpTarget) Descriptor() ([]byte, []int) {
	return fileDescriptor_09bcb7a7db58f7d2, []int{0, 0}
}

func (m *CreatePeerRequest_RtpTarget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePeerRequest_RtpTarget.Unmarshal(m, b)
}
func (m *CreatePeerRequest_RtpTarget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePeerRequest_RtpTarget.Marshal(b, m, deterministic)
}
func (m *CreatePeerRequest_RtpTarget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePeerRequest_RtpTarget.Merge(m, src)
}
func (m *CreatePeerRequest_RtpTarget) XXX_Size() int {
	return xxx_messageInfo_CreatePeerRequest_RtpTarget.Size(m)
}
func (m *CreatePeerRequest_RtpTarget) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePeerRequest_RtpTarget.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePeerRequest_RtpTarget proto.InternalMessageInfo

func (m *CreatePeerRequest_RtpTarget) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *CreatePeerRequest_RtpTarget) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type CreatePeerResponse struct {
	OfferSdp             string   `protobuf:"bytes,1,opt,name=offer_sdp,json=offerSdp,proto3" json:"offer_sdp,omitempty"`
	RtpSdp               string   `protobuf:"bytes,2,opt,name=rtp_sdp,json=rtpSdp,proto3" json:"rtp_sdp,omitempty"`
	PeerId               string   `protobuf:"bytes,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePeerResponse) Reset()         { *m = CreatePeerResponse{} }
func (m *CreatePeerResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePeerResponse) ProtoMessage()    {}
func (*CreatePeerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_09bcb7a7db58f7d2, []int{1}
}

func (m *CreatePeerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePeerResponse.Unmarshal(m, b)
}
func (m *CreatePeerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePeerResponse.Marshal(b, m, deterministic)
}
func (m *CreatePeerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePeerResponse.Merge(m, src)
}
func (m *CreatePeerResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePeerResponse.Size(m)
}
func (m *CreatePeerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePeerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePeerResponse proto.InternalMessageInfo

func (m *CreatePeerResponse) GetOfferSdp() string {
	if m != nil {
		return m.OfferSdp
	}
	return ""
}

func (m *CreatePeerResponse) GetRtpSdp() string {
	if m != nil {
		return m.RtpSdp
	}
	return ""
}

func (m *CreatePeerResponse) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

type SetRemoteDescriptionRequest struct {
	AnswerSdp            string   `protobuf:"bytes,1,opt,name=answer_sdp,json=answerSdp,proto3" json:"answer_sdp,omitempty"`
	PeerId               string   `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRemoteDescriptionRequest) Reset()         { *m = SetRemoteDescriptionRequest{} }
func (m *SetRemoteDescriptionRequest) String() string { return proto.CompactTextString(m) }
func (*SetRemoteDescriptionRequest) ProtoMessage()    {}
func (*SetRemoteDescriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_09bcb7a7db58f7d2, []int{2}
}

func (m *SetRemoteDescriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRemoteDescriptionRequest.Unmarshal(m, b)
}
func (m *SetRemoteDescriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRemoteDescriptionRequest.Marshal(b, m, deterministic)
}
func (m *SetRemoteDescriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRemoteDescriptionRequest.Merge(m, src)
}
func (m *SetRemoteDescriptionRequest) XXX_Size() int {
	return xxx_messageInfo_SetRemoteDescriptionRequest.Size(m)
}
func (m *SetRemoteDescriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRemoteDescriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRemoteDescriptionRequest proto.InternalMessageInfo

func (m *SetRemoteDescriptionRequest) GetAnswerSdp() string {
	if m != nil {
		return m.AnswerSdp
	}
	return ""
}

func (m *SetRemoteDescriptionRequest) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

type SetRemoteDescriptionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRemoteDescriptionResponse) Reset()         { *m = SetRemoteDescriptionResponse{} }
func (m *SetRemoteDescriptionResponse) String() string { return proto.CompactTextString(m) }
func (*SetRemoteDescriptionResponse) ProtoMessage()    {}
func (*SetRemoteDescriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_09bcb7a7db58f7d2, []int{3}
}

func (m *SetRemoteDescriptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRemoteDescriptionResponse.Unmarshal(m, b)
}
func (m *SetRemoteDescriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRemoteDescriptionResponse.Marshal(b, m, deterministic)
}
func (m *SetRemoteDescriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRemoteDescriptionResponse.Merge(m, src)
}
func (m *SetRemoteDescriptionResponse) XXX_Size() int {
	return xxx_messageInfo_SetRemoteDescriptionResponse.Size(m)
}
func (m *SetRemoteDescriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRemoteDescriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetRemoteDescriptionResponse proto.InternalMessageInfo

type AddIceCandidateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddIceCandidateRequest) Reset()         { *m = AddIceCandidateRequest{} }
func (m *AddIceCandidateRequest) String() string { return proto.CompactTextString(m) }
func (*AddIceCandidateRequest) ProtoMessage()    {}
func (*AddIceCandidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_09bcb7a7db58f7d2, []int{4}
}

func (m *AddIceCandidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddIceCandidateRequest.Unmarshal(m, b)
}
func (m *AddIceCandidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddIceCandidateRequest.Marshal(b, m, deterministic)
}
func (m *AddIceCandidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddIceCandidateRequest.Merge(m, src)
}
func (m *AddIceCandidateRequest) XXX_Size() int {
	return xxx_messageInfo_AddIceCandidateRequest.Size(m)
}
func (m *AddIceCandidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddIceCandidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddIceCandidateRequest proto.InternalMessageInfo

type AddIceCandidateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddIceCandidateResponse) Reset()         { *m = AddIceCandidateResponse{} }
func (m *AddIceCandidateResponse) String() string { return proto.CompactTextString(m) }
func (*AddIceCandidateResponse) ProtoMessage()    {}
func (*AddIceCandidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_09bcb7a7db58f7d2, []int{5}
}

func (m *AddIceCandidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddIceCandidateResponse.Unmarshal(m, b)
}
func (m *AddIceCandidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddIceCandidateResponse.Marshal(b, m, deterministic)
}
func (m *AddIceCandidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddIceCandidateResponse.Merge(m, src)
}
func (m *AddIceCandidateResponse) XXX_Size() int {
	return xxx_messageInfo_AddIceCandidateResponse.Size(m)
}
func (m *AddIceCandidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddIceCandidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddIceCandidateResponse proto.InternalMessageInfo

type DestroyPeerRequest struct {
	PeerId               string   `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DestroyPeerRequest) Reset()         { *m = DestroyPeerRequest{} }
func (m *DestroyPeerRequest) String() string { return proto.CompactTextString(m) }
func (*DestroyPeerRequest) ProtoMessage()    {}
func (*DestroyPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_09bcb7a7db58f7d2, []int{6}
}

func (m *DestroyPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyPeerRequest.Unmarshal(m, b)
}
func (m *DestroyPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyPeerRequest.Marshal(b, m, deterministic)
}
func (m *DestroyPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyPeerRequest.Merge(m, src)
}
func (m *DestroyPeerRequest) XXX_Size() int {
	return xxx_messageInfo_DestroyPeerRequest.Size(m)
}
func (m *DestroyPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyPeerRequest proto.InternalMessageInfo

func (m *DestroyPeerRequest) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

type DestroyPeerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DestroyPeerResponse) Reset()         { *m = DestroyPeerResponse{} }
func (m *DestroyPeerResponse) String() string { return proto.CompactTextString(m) }
func (*DestroyPeerResponse) ProtoMessage()    {}
func (*DestroyPeerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_09bcb7a7db58f7d2, []int{7}
}

func (m *DestroyPeerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyPeerResponse.Unmarshal(m, b)
}
func (m *DestroyPeerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyPeerResponse.Marshal(b, m, deterministic)
}
func (m *DestroyPeerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyPeerResponse.Merge(m, src)
}
func (m *DestroyPeerResponse) XXX_Size() int {
	return xxx_messageInfo_DestroyPeerResponse.Size(m)
}
func (m *DestroyPeerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyPeerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyPeerResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreatePeerRequest)(nil), "r5.CreatePeerRequest")
	proto.RegisterType((*CreatePeerRequest_RtpTarget)(nil), "r5.CreatePeerRequest.RtpTarget")
	proto.RegisterType((*CreatePeerResponse)(nil), "r5.CreatePeerResponse")
	proto.RegisterType((*SetRemoteDescriptionRequest)(nil), "r5.SetRemoteDescriptionRequest")
	proto.RegisterType((*SetRemoteDescriptionResponse)(nil), "r5.SetRemoteDescriptionResponse")
	proto.RegisterType((*AddIceCandidateRequest)(nil), "r5.AddIceCandidateRequest")
	proto.RegisterType((*AddIceCandidateResponse)(nil), "r5.AddIceCandidateResponse")
	proto.RegisterType((*DestroyPeerRequest)(nil), "r5.DestroyPeerRequest")
	proto.RegisterType((*DestroyPeerResponse)(nil), "r5.DestroyPeerResponse")
}

func init() { proto.RegisterFile("r5.proto", fileDescriptor_09bcb7a7db58f7d2) }

var fileDescriptor_09bcb7a7db58f7d2 = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xa6, 0x0d, 0xf1, 0x94, 0x0f, 0xb1, 0xb4, 0x8d, 0x71, 0xf8, 0x88, 0x2c, 0x0e, 0xb9,
	0x90, 0x43, 0xab, 0xdc, 0x40, 0x02, 0xb5, 0x97, 0x4a, 0x1c, 0xd0, 0x86, 0x9e, 0x38, 0x58, 0xc6,
	0x3b, 0x85, 0x3d, 0x90, 0x5d, 0x66, 0x27, 0x45, 0xfc, 0x11, 0xfe, 0x0a, 0x7f, 0x0f, 0x79, 0xec,
	0x86, 0x24, 0x36, 0x88, 0x9b, 0xe7, 0xbd, 0x7d, 0x6f, 0x67, 0xde, 0xac, 0x61, 0x48, 0xf3, 0x99,
	0x27, 0xc7, 0x4e, 0xc5, 0x34, 0xcf, 0x7f, 0xc6, 0xf0, 0xf0, 0x8c, 0xb0, 0x64, 0x7c, 0x8f, 0x48,
	0x1a, 0xbf, 0xad, 0x30, 0xb0, 0x3a, 0x84, 0xfd, 0x72, 0x65, 0xac, 0x4b, 0xa3, 0x49, 0x34, 0x1d,
	0xea, 0xa6, 0xa8, 0xd1, 0x6b, 0x6b, 0xd0, 0xa5, 0x71, 0x83, 0x4a, 0xa1, 0x5e, 0x41, 0x22, 0x74,
	0x41, 0xec, 0xd3, 0xdb, 0x93, 0x68, 0x7a, 0x70, 0xf2, 0x7c, 0x46, 0xf3, 0x59, 0xc7, 0x75, 0xa6,
	0xd9, 0x7f, 0x28, 0xe9, 0x33, 0xb2, 0x1e, 0x8a, 0x42, 0xb3, 0xaf, 0xd5, 0x62, 0x23, 0xea, 0xbd,
	0xff, 0x54, 0x8b, 0xa2, 0x56, 0xbf, 0x80, 0xfb, 0xb6, 0xc2, 0x22, 0x20, 0x5d, 0x23, 0x15, 0x2b,
	0xb2, 0xe9, 0xfe, 0x24, 0x9a, 0x26, 0xfa, 0xae, 0xad, 0x70, 0x21, 0xe0, 0x25, 0xd9, 0xec, 0x14,
	0x92, 0xb5, 0x58, 0x29, 0xd8, 0xfb, 0xe2, 0x02, 0xcb, 0x64, 0x89, 0x96, 0xef, 0x1a, 0xf3, 0x8e,
	0x58, 0xe6, 0xba, 0xa7, 0xe5, 0x3b, 0xaf, 0x40, 0x6d, 0xf6, 0x10, 0xbc, 0x5b, 0x06, 0x54, 0x63,
	0x48, 0xdc, 0xd5, 0x15, 0x52, 0x11, 0x8c, 0x6f, 0x2d, 0x86, 0x02, 0x2c, 0x8c, 0x57, 0x23, 0xb8,
	0x43, 0xec, 0x85, 0x8a, 0x85, 0x1a, 0x10, 0xfb, 0x96, 0xf0, 0x88, 0x54, 0x58, 0x23, 0x01, 0x25,
	0x7a, 0x50, 0x97, 0x17, 0x26, 0xbf, 0x84, 0xf1, 0x02, 0x59, 0xe3, 0x57, 0xc7, 0x78, 0x8e, 0xa1,
	0x22, 0xeb, 0xd9, 0xba, 0xe5, 0xcd, 0x1a, 0x9e, 0x02, 0x94, 0xcb, 0xf0, 0x7d, 0xeb, 0xba, 0xa4,
	0x41, 0x76, 0x6c, 0xe3, 0x2d, 0xdb, 0x67, 0xf0, 0xa4, 0xdf, 0xb6, 0x99, 0x22, 0x4f, 0xe1, 0xf8,
	0xad, 0x31, 0x17, 0x15, 0x9e, 0x95, 0x4b, 0x63, 0x4d, 0xc9, 0xd8, 0xde, 0x98, 0x3f, 0x86, 0x51,
	0x87, 0x69, 0x45, 0x2f, 0x41, 0x9d, 0x63, 0x60, 0x72, 0x3f, 0x36, 0x5f, 0xca, 0x46, 0x0f, 0xd1,
	0x56, 0x0f, 0x47, 0xf0, 0x68, 0xeb, 0x78, 0xe3, 0x72, 0xf2, 0x2b, 0x86, 0x44, 0xcf, 0xeb, 0xdd,
	0xd8, 0x0a, 0xd5, 0x6b, 0x80, 0x3f, 0x21, 0xab, 0xa3, 0xde, 0xc5, 0x67, 0xc7, 0xbb, 0x70, 0xdb,
	0xd0, 0x2d, 0xf5, 0x11, 0x0e, 0xfb, 0xe6, 0x54, 0xf2, 0x82, 0xfe, 0x11, 0x6c, 0x36, 0xf9, 0xfb,
	0x81, 0xb5, 0xf9, 0x3b, 0x78, 0xb0, 0x13, 0x85, 0xca, 0x6a, 0x59, 0x7f, 0x72, 0xd9, 0xb8, 0x97,
	0x5b, 0xbb, 0xbd, 0x81, 0x83, 0x8d, 0x38, 0x94, 0xcc, 0xd4, 0x8d, 0x33, 0x1b, 0x75, 0xf0, 0x1b,
	0x87, 0x4f, 0x03, 0xf9, 0x69, 0x4f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x3c, 0xe0, 0x83,
	0xc0, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// R5ServiceClient is the client API for R5Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type R5ServiceClient interface {
	CreatePeer(ctx context.Context, in *CreatePeerRequest, opts ...grpc.CallOption) (*CreatePeerResponse, error)
	SetRemoteDescription(ctx context.Context, in *SetRemoteDescriptionRequest, opts ...grpc.CallOption) (*SetRemoteDescriptionResponse, error)
	AddIceCandidate(ctx context.Context, in *AddIceCandidateRequest, opts ...grpc.CallOption) (*AddIceCandidateResponse, error)
	DestroyPeer(ctx context.Context, in *DestroyPeerRequest, opts ...grpc.CallOption) (*DestroyPeerResponse, error)
}

type r5ServiceClient struct {
	cc *grpc.ClientConn
}

func NewR5ServiceClient(cc *grpc.ClientConn) R5ServiceClient {
	return &r5ServiceClient{cc}
}

func (c *r5ServiceClient) CreatePeer(ctx context.Context, in *CreatePeerRequest, opts ...grpc.CallOption) (*CreatePeerResponse, error) {
	out := new(CreatePeerResponse)
	err := c.cc.Invoke(ctx, "/r5.R5Service/CreatePeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *r5ServiceClient) SetRemoteDescription(ctx context.Context, in *SetRemoteDescriptionRequest, opts ...grpc.CallOption) (*SetRemoteDescriptionResponse, error) {
	out := new(SetRemoteDescriptionResponse)
	err := c.cc.Invoke(ctx, "/r5.R5Service/SetRemoteDescription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *r5ServiceClient) AddIceCandidate(ctx context.Context, in *AddIceCandidateRequest, opts ...grpc.CallOption) (*AddIceCandidateResponse, error) {
	out := new(AddIceCandidateResponse)
	err := c.cc.Invoke(ctx, "/r5.R5Service/AddIceCandidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *r5ServiceClient) DestroyPeer(ctx context.Context, in *DestroyPeerRequest, opts ...grpc.CallOption) (*DestroyPeerResponse, error) {
	out := new(DestroyPeerResponse)
	err := c.cc.Invoke(ctx, "/r5.R5Service/DestroyPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// R5ServiceServer is the server API for R5Service service.
type R5ServiceServer interface {
	CreatePeer(context.Context, *CreatePeerRequest) (*CreatePeerResponse, error)
	SetRemoteDescription(context.Context, *SetRemoteDescriptionRequest) (*SetRemoteDescriptionResponse, error)
	AddIceCandidate(context.Context, *AddIceCandidateRequest) (*AddIceCandidateResponse, error)
	DestroyPeer(context.Context, *DestroyPeerRequest) (*DestroyPeerResponse, error)
}

// UnimplementedR5ServiceServer can be embedded to have forward compatible implementations.
type UnimplementedR5ServiceServer struct {
}

func (*UnimplementedR5ServiceServer) CreatePeer(ctx context.Context, req *CreatePeerRequest) (*CreatePeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePeer not implemented")
}
func (*UnimplementedR5ServiceServer) SetRemoteDescription(ctx context.Context, req *SetRemoteDescriptionRequest) (*SetRemoteDescriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRemoteDescription not implemented")
}
func (*UnimplementedR5ServiceServer) AddIceCandidate(ctx context.Context, req *AddIceCandidateRequest) (*AddIceCandidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddIceCandidate not implemented")
}
func (*UnimplementedR5ServiceServer) DestroyPeer(ctx context.Context, req *DestroyPeerRequest) (*DestroyPeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyPeer not implemented")
}

func RegisterR5ServiceServer(s *grpc.Server, srv R5ServiceServer) {
	s.RegisterService(&_R5Service_serviceDesc, srv)
}

func _R5Service_CreatePeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(R5ServiceServer).CreatePeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/r5.R5Service/CreatePeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(R5ServiceServer).CreatePeer(ctx, req.(*CreatePeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _R5Service_SetRemoteDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRemoteDescriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(R5ServiceServer).SetRemoteDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/r5.R5Service/SetRemoteDescription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(R5ServiceServer).SetRemoteDescription(ctx, req.(*SetRemoteDescriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _R5Service_AddIceCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddIceCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(R5ServiceServer).AddIceCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/r5.R5Service/AddIceCandidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(R5ServiceServer).AddIceCandidate(ctx, req.(*AddIceCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _R5Service_DestroyPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(R5ServiceServer).DestroyPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/r5.R5Service/DestroyPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(R5ServiceServer).DestroyPeer(ctx, req.(*DestroyPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _R5Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "r5.R5Service",
	HandlerType: (*R5ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePeer",
			Handler:    _R5Service_CreatePeer_Handler,
		},
		{
			MethodName: "SetRemoteDescription",
			Handler:    _R5Service_SetRemoteDescription_Handler,
		},
		{
			MethodName: "AddIceCandidate",
			Handler:    _R5Service_AddIceCandidate_Handler,
		},
		{
			MethodName: "DestroyPeer",
			Handler:    _R5Service_DestroyPeer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "r5.proto",
}
